src/Web/Controllers/DocumentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShaBoo.Domain.Services;
using ShaBoo.Web.ViewModels;

namespace ShaBoo.Web.Controllers
{
    using Newtonsoft.Json.Linq;

    using ShaBoo.Services.Util;

    //[Authorize(Roles = "User")]
    public class DocumentController : Controller
    {
        #region ctor
        private IBLLService _service;
        public DocumentController(IBLLService service)
        {
            _service = service;
        }
        #endregion

        /// <summary>
        /// 文件上传目录
        /// </summary>
        private string StorageRoot
        {
            get { return Path.Combine(System.Web.HttpContext.Current.Server.MapPath("~/Files/")); } //Path should! always end with '/'
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(DocumentViewModels.UploadModel model)
        {
            string path = StorageRoot;
            string filePath = Path.Combine(path, model.FileName);
            var suffix = Path.GetExtension(filePath);
            var size = ((Int32)new System.IO.FileInfo(filePath).Length) / (1024 * 1024);
            _service.DocumentService.CreateNewUploadedDocument(
                model.Title, model.FstClass, model.SndClass, model.TrdClass,
                model.Tags, model.Intro,
                filePath, size, suffix,
                0, 0, DateTime.UtcNow, User.Identity.Name);
            return Content("谢谢，上传成功", "text/html");
        }


        /// <summary>
        /// 上传文件
        /// </summary>
        /// <param name="qqfile"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult FileUpload(string qqfile)
        {
            var file = string.Empty;

            try
            {
                var stream = Request.InputStream;
                if (String.IsNullOrEmpty(Request["qqfile"]))
                {
                    // IE
                    HttpPostedFileBase postedFile = Request.Files[0];
                    stream = postedFile.InputStream;
                    file = Path.Combine(StorageRoot, Path.GetFileName(postedFile.FileName));
                }
                else
                {
                    //Webkit, Mozilla
                    file = Path.Combine(StorageRoot, qqfile);
                }

                var buffer = new byte[stream.Length];
                stream.Read(buffer, 0, buffer.Length);
                System.IO.File.WriteAllBytes(file, buffer);
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message }, "application/json");
            }

            return Json(new { success = true }, "text/html");
        }

        public ActionResult Single(int id)
        {
            var document = _service.DocumentService.GetDocuments().Where(_ => _.ID == id).FirstOrDefault();
            var model = new DocumentViewModels.DownloadModel
                {
                    ID = id,
                    Title = document.Title,
                    Downloads = document.Downloads,
                    Views = document.Views,
                    Suffix = document.Suffix,
                    Intro = document.Intro,
                    UploadedOn = document.UploadedOn,
                    User = document.Profile.UserName,
                    Size = document.Size
                };
            return View(model);
        }

        public ActionResult Download(int id)
        {

            var document = _service.DocumentService.GetDocument(id);

            if (document != null)
            {
                var path = document.Path;
                string filename = document.Title + Path.GetExtension(path);
                string contentType = RegistryMimeTypeLookup.GetMimeType(path);
                var file = new FileInfo(path);
                if (file.Exists)
                {
                    return File(document.Path, contentType, filename);
                }
            }
            return null;
        }

        public ActionResult Category(int id)
        {
            return View();
        }

        #region Ajax获得三级分类
        [HttpPost]
        public ActionResult GetFstClasses()
        {
            try
            {
                var fstClassList = _service.ClassService.GetFstClasses();

                var returndata = from fstClass in fstClassList
                                 select new
                                 {
                                     ID = fstClass.ID,
                                     Name = fstClass.Name
                                 };

                return Json(new { ok = true, data = returndata, message = "ok" });
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, message = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult GetSndClasses(int id)
        {
            try
            {
                var sndClassList = _service.ClassService.GetSndClasses();

                var returndata = from sndClass in sndClassList
                                 where sndClass.FstClassID == id
                                 select new
                                 {
                                     ID = sndClass.ID,
                                     Name = sndClass.Name
                                 };

                return Json(new { ok = true, data = returndata, message = "ok" });
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, message = ex.Message });
            }
        }

        [HttpPost]
        public ActionResult GetTrdClasses(int id)
        {
            try
            {
                var trdClassList = _service.ClassService.GetTrdClasses();

                var returndata = from trdClass in trdClassList
                                 where trdClass.SndClassID == id
                                 select new
                                 {
                                     ID = trdClass.ID,
                                     Name = trdClass.Name
                                 };

                return Json(new { ok = true, data = returndata, message = "ok" });
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, message = ex.Message });
            }
        }
        #endregion
    }
}

src/Web/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShaBoo.Web.Controllers
{
    using ShaBoo.Domain.Services;
    using ShaBoo.Web.ViewModels;

    [Authorize(Roles = "User")]
    public class ProfileController : Controller
    {
        #region ctor
        private IBLLService _service;
        public ProfileController(IBLLService service)
        {
            _service = service;
        }
        #endregion

        public ActionResult Index(string name)
        {
            var model = new ProfileViewModels.IndexModel();
            model.Name = name;
            model.Point = _service.ProfileService.GetProfile(name).Point;

            model.UploadedDocuments = _service.DocumentService.GetDocuments().Where(_ => _.Profile.UserName == name);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            return this.View();
        }

        [HttpPost]
        public ActionResult Edit(ProfileViewModels.EditModel model)
        {


            return this.View(model);
        }

    }
}

src/Web/Views/Shared/_LogOnPartial.cshtml
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Scripts/fancybox/jquery.fancybox.css")" media="all" />
<style type="text/css">
    #loginbox
    {
        width: 400px;
        height: 200px;
    }
    
    #loginbox form
    {
        width: 300px;
        height: 200px;
        margin-top: 60px;
        margin-right: auto;
        margin-left: auto;
        margin-bottom: 0;
    }
    .logintext
    {
        font-size: 14px;
        color: #333;
    }
    input.login_username
    {
        width: 230px;
        height: 20px;
        line-height: 20px;
    }
    input.login_pw
    {
        width: 230px;
        height: 20px;
        line-height: 20px;
        margin-top: 15px;
    }
    div.rememandsub
    {
        margin-top: 15px;
        font-size: 14px;
        line-height: 20px;
        width: 300px;
    }
    input.mem_checkbox
    {
        margin-right: 8px;
        virtical-align: middle;
    }
    lebel.mem_text
    {
        virtical-align: middle;
    }
    input.login_submit
    {
        font-size: 14px;
        color: #FFF;
        letter-spacing: 0.4em;
        text-align: center;
        width: 58px;
        height: 24px;
        padding-left: 13px;
        _padding-left: 0;
        padding-bottom: 3px;
        background-color: #92C976;
        border: 1px solid #79B05F;
        cursor: hand;
        float: right;
    }
</style>
@if (Request.IsAuthenticated)
{
    <div id="logout">
        <ul class="inline">
            <li><a href="">欢迎您，@User.Identity.Name</a></li>
            <li><a href="@Url.Action("Index", "Profile", new { name = User.Identity.Name })">我的文档</a></li>
            <li><a href="@Url.Action("LogOff", "Account")">退出</a></li>
        </ul>
    </div>
}
else
{
    <div id="login">
        <ul class="inline">
            <li><a href="@Url.Action("Register", "Account")">注册</a></li>
            <li>|</li>
            <li><a href="#loginbox" class="fancybox">登录</a></li>
        </ul>
    </div>
}
<div id="loginbox" style="display:none;">
		<form action="">
			<span class="logintext">用户名：</span>
			<input type="text" name="" id="" class="login_username"/>
			<br/>
			<span class="logintext">密&nbsp 码：</span>
			<input type="password" name="" id="" class="login_pw"/>
			<br/>
			<div class="rememandsub"><input type="checkbox" name="" id="" class="mem_checkbox"/><label class="mem_text">记住我</label><input type="submit" value="登录" class="login_submit"/></div>
		</form>
	</div>
<script type="text/javascript" src="@Url.Content("~/Scripts/shaboo/jquery.mousewheel-3.0.6.pack.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/fancybox/jquery.fancybox.js")"></script>
	<script type="text/javascript">
	    $(document).ready(function () {
	        $(".fancybox").fancybox();
	    });
	</script>

src/Web/Views/Shared/_RightSidebar.cshtml
<div id="rightsidebar">
    <div class="uploadlink">
        <p class="docnum">
            当前已有<span>12345</span>份文档</p>
        <a href="@Url.Action("Upload", "Document")">
            <img src="@Url.Content("~/Content/images//uploaddocs.jpg")" alt="分享我的文档" /></a>
    </div>
    <div class="latest">
        <h3>
            最新上传</h3>
        <hr />
        <ul>
            <li><a href="">
                <img src="@Url.Content("~/Content/images//doctypeicon/ppt.jpg")" alt="PPT" class="doctypeicon" />马克思主义基本原理</a></li>
            <li><a href="">
                <img src="@Url.Content("~/Content/images//doctypeicon/pdf.jpg")" alt="PDF" class="doctypeicon" />2011大学毕业生自我鉴定</a></li>
            <li><a href="">
                <img src="@Url.Content("~/Content/images//doctypeicon/doc.jpg")" alt="WORD" class="doctypeicon" />绿色环保宣传标语</a></li>
            <li><a href="">
                <img src="@Url.Content("~/Content/images//doctypeicon/ppt.jpg")" alt="PPT" class="doctypeicon" />绿色环保宣传标语</a></li>
            <li><a href="">
                <img src="@Url.Content("~/Content/images//doctypeicon/ppt.jpg")" alt="PPT" class="doctypeicon" />信号与线性系统</a></li>
        </ul>
    </div>
    <div class="recommend">
        <a href="">
            <h3>
                每周推荐</h3>
        </a>
        <hr />
        <!-- "rb"=recommend book -->
        <div id="rbglider">
            <div id="rslider">
                <ul>
                    <li>
                        <div class="section">
                            <div class="cover">
                                <a href="#">
                                    <img src="@Url.Content("~/Content/images//bookcover.jpg")" alt="例外的挑战" /></a>
                            </div>
                            <p class="rbtitle">
                                <a href="#">《例外的挑战》0</a></p>
                            <p class="rbauthor">
                                作者：乔治·施瓦布</p>
                            <p class="rbindroduction">
                                简介：德国法学家卡尔·施米特深刻地影响力上个世纪的西方政治和法学思想，然而他的生平和著作也激起了相当大的争议。本书是揭示</p>
                        </div>
                    </li>
                    <li>
                        <div class="section">
                            <div class="cover">
                                <a href="">
                                    <img src="@Url.Content("~/Content/images//bookcover.jpg")" alt="例外的挑战" /></a>
                            </div>
                            <p class="rbtitle">
                                <a href="#">《例外的挑战》1</a></p>
                            <p class="rbauthor">
                                作者：乔治·施瓦布</p>
                            <p class="rbindroduction">
                                简介：德国法学家卡尔·施米特深刻地影响力上个世纪的西方政治和法学思想，然而他的生平和著作也激起了相当大的争议。本书是揭示</p>
                        </div>
                    </li>
                    <li>
                        <div class="section">
                            <div class="cover">
                                <a href="">
                                    <img src="@Url.Content("~/Content/images//bookcover.jpg")" alt="例外的挑战" /></a>
                            </div>
                            <p class="rbtitle">
                                <a href="#">《例外的挑战》2</a></p>
                            <p class="rbauthor">
                                作者：乔治·施瓦布</p>
                            <p class="rbindroduction">
                                简介：德国法学家卡尔·施米特深刻地影响力上个世纪的西方政治和法学思想，然而他的生平和著作也激起了相当大的争议。本书是揭示</p>
                        </div>
                    </li>
                    <li>
                        <div class="section">
                            <div class="cover">
                                <a href="">
                                    <img src="@Url.Content("~/Content/images//bookcover.jpg")" alt="例外的挑战" /></a>
                            </div>
                            <p class="rbtitle">
                                <a href="#">《例外的挑战》3</a></p>
                            <p class="rbauthor">
                                作者：乔治·施瓦布</p>
                            <p class="rbindroduction">
                                简介：德国法学家卡尔·施米特深刻地影响力上个世纪的西方政治和法学思想，然而他的生平和著作也激起了相当大的争议。本书是揭示</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <!--<p id="rcontrols">
						<a href="javascript:void(0);" id="prevBtn" ></a>
						<a href="javascript:void(0);" id="nextBtn" ></a>
						<script type="text/javascript" charset="utf-8">
							
	  					</script>
					</p>-->
    </div>
    @*<div class="rank">
        <h3>
            积分排行</h3>
        <hr />
        <ul class="inline">
            <li><a href="" id="weeklink" class="active">本周</a></li>
            <li>|</li>
            <li><a href="" id="monthlink" class="">本月</a></li>
            <li>|</li>
            <li><a href="" id="totallink" class="">总计</a></li>
        </ul>
        <!-- "rweek"=rank week" -->
        <div id="rweek" class="">
            <ol>
                <li><a href="">wusername123</a></li>
                <li><a href="">wusername123</a></li>
                <li><a href="">wusername123</a></li>
                <li><a href="">wusername123</a></li>
                <li><a href="">wusername123</a></li>
                <li><a href="">wusername123</a></li>
                <li><a href="">wusername123</a></li>
                <li><a href="">wusername123</a></li>
                <li><a href="">wusername123</a></li>
                <li><a href="">wusername123</a></li>
            </ol>
        </div>
        <div id="rmonth" class="no-display">
            <ol>
                <li><a href="">musername123</a></li>
                <li><a href="">musername123</a></li>
                <li><a href="">musername123</a></li>
                <li><a href="">musername123</a></li>
                <li><a href="">musername123</a></li>
                <li><a href="">musername123</a></li>
                <li><a href="">musername123</a></li>
                <li><a href="">musername123</a></li>
                <li><a href="">musername123</a></li>
                <li><a href="">musername123</a></li>
            </ol>
        </div>
        <div id="rtotal" class="no-display">
            <ol>
                <li><a href="">tusername123</a></li>
                <li><a href="">tusername123</a></li>
                <li><a href="">tusername123</a></li>
                <li><a href="">tusername123</a></li>
                <li><a href="">tusername123</a></li>
                <li><a href="">tusername123</a></li>
                <li><a href="">tusername123</a></li>
                <li><a href="">tusername123</a></li>
                <li><a href="">tusername123</a></li>
                <li><a href="">tusername123</a></li>
            </ol>
        </div>
    </div>*@
</div>